<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "idp"
 *
 * Auto generated by Extension Builder 2019-05-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SAML IDP 2.0 Single Sign On (SSO) - Login using Typo3 credentials',
    'description' => 'Typo3 as IdP Single Sign On (SSO) extension allows users residing in your Typo3 site to login to your SAML 2.0 Compliant Service Provider. Login into your websites (Service Providers) using Typo3 credentials. This extension enables your Typo3 site to operate as a SAML 2.0 Identity Provider, which can be set to build trust between the Typo3 site and multiple SAML 2.0 compliant Service Providers in order to securely authenticate users who use the Typo3 site.',
    'author' => 'miniOrange',
    'state' => 'stable',
    'shy' => '',
    'icon' => 'EXT:idp/Resources/Public/Icons/miniorange.svg',
    'version' => '1.0.4',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-12.5.13',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'psr-4' => [
            'Miniorange\\Idp\\' => 'Classes/',
        ]
    ],
];